### ISSUE TITLE
`nvm use` in config.fish interrupts SCP transfer

### ISSUE THREAD

**Issue by nc7s** [fisherman/fnm#165]
Hi,

It's a little annoying that when I have `nvm use` in my `config.fish` and `scp` from somewhere else, `nvm use` would say "Now using Node vx.y.z" then `scp` just exits, no transfer happens. Back to normal when `nvm use` is removed. But I want to have Node ready on remote sessions.

**Comment by jorgebucaran** [comment]
Do it only if interactive:

```fish
if status is-interactive
    nvm use x.z.y
end
```

If that doesn't help, instead of using `nvm use` in your config.fish, try setting `nvm_default_version` (once) in the CLI. 

```fish
set --universal nvm_default_version x.y.z
```

**Comment by nc7s** [comment]
`set -xU nvm_default_version x.y.z` solved it, and wouldn't say "Now using" on every new session startup. Thank you 😄
