### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by metacortexplus** [fisherman/fnm#166]
That is what I get.

```
➜  ~ nvm list
     v16.8.0 latest 
```

**Comment by jorgebucaran** [comment]
Looks good to me. Did you read the documentation?

**Comment by metacortexplus** [comment]
I need to run `set --universal nvm_default_version v16`
 or run `nvm use v16` every time I run shell, right? Ok, excuse me :)

**Comment by jorgebucaran** [comment]
Yep, you got it! 🙌
