### ISSUE TITLE
Can't update index, host unavailable: "https://nodejs.org/dist"

### ISSUE THREAD

**Issue by sophiiss** [fisherman/fnm#185]
I reinstalled my OS and now I get this error when I try to run `nvm install` or `nvm list-remote`

`Can't update index, host unavailable: "https://nodejs.org/dist"`

**Comment by jorgebucaran** [comment]
What is your OS? You just re-installed, right? Meaning, reinstalling didn't wipe out your disk or Fish.

**Comment by asutula** [comment]
Same problem here. Brand new MacBook Pro with the M1 Pro chip.

**Comment by asutula** [comment]
Full error here:
```
warning: An error occurred while redirecting file '/Users/aaron/.local/share/nvm/.index.temp'
warning: Path '/Users/aaron/.local/share/nvm' does not exist
nvm: Can't update index, host unavailable: "https://nodejs.org/dist"
```

**Comment by asutula** [comment]
Ok, uninstalled and re-installed `nvm.fish` using `fisher` and that seems to have fixed it. I believe I migrated all my Fish settings and plugins from my old computer (an Intel chip MacBook Pro), so likely something incompatible there.
