### ISSUE TITLE
⚠️ Breaking change: Renaming fin to `fnm'

### ISSUE THREAD

**Issue by brj** [fisherman/fnm#33]
I've been thinking about this for a while, and I'd like to rename `fin` to something else. 

Some ideas:

* nv
* nvn
* **fnm** (by @mrak)
* nenv

The problem with this is that it's not easy to make this change backward compatible, so the best way to upgrade to this future version would be:

```fish
rm -rf $fin_config
rm -rf $fin_cache
fisher rm fin
fisher i NEW_FIN
# That's it.
```

**Comment by mrak** [comment]
`fnm` for "fish node manager"?

**Comment by brj** [comment]
That sounds good too!

**Comment by brj** [comment]
@fisherman/all Sorry to ping all the team, but just wanted to get your attention wrt to this issue. Feel free to ignore if you don't use `fin`, but by all means please share your opinion if there is any.
