### ISSUE TITLE
Completions 

### ISSUE THREAD

**Issue by FabioAntunes** [fisherman/fnm#37]
So it seems that the pull request that was merged it doesn't fix anything, but it seems that the problem is not with us but with the npm completions, more info here https://github.com/fish-shell/fish-shell/issues/3158

@brj Sorry for creating a pull request that doesn't fix anything. I think it's better to undo the pull request, fortunately it's just one line change.

I'm going to take a look at the [npm completions](https://github.com/fish-shell/fish-shell/blob/36691df6fe4667645b71b550ce5eea90762ac23a/share/completions/npm.fish) and see if I can find a solution for that

**Comment by FabioAntunes** [comment]
So I made a pull request https://github.com/fish-shell/fish-shell/pull/3159

The problem was that npm was being called for the completions, but they were not forcing the command so any alias would be called instead.

This will fix https://github.com/fisherman/fnm/issues/35 and https://github.com/fisherman/nvm/issues/4 for good

**Comment by brj** [comment]
Great, thanks @FabioAntunes.

**Comment by FabioAntunes** [comment]
@brj things are solved this commit fixes the completions with alias https://github.com/fish-shell/fish-shell/commit/10661bb024cd87fdb5452b86fcc74a58f7f678f1 

For those who don't want to wait for the next fish release to have completions, you just need to do:

`wget https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/completions/npm.fish`

and then do `sudo mv npm.fish /usr/share/fish/completions/`
